### ISSUE TITLE
28. Admin Merchants Grouped by Status

### ISSUE THREAD

**Issue by JorjaF** [z-fitch/little-shop-7#46]
As an admin,
When I visit the admin merchants index (/admin/merchants)
Then I see two sections, one for "Enabled Merchants" and one for "Disabled Merchants"
And I see that each Merchant is listed in the appropriate section

**Comment by Daniel-Gallagher92** [comment]
I believe I got this working properly, but check it out when you get around to it plz 🙏

**Comment by Daniel-Gallagher92** [comment]
Added note: I did not touch your tests, but I think what you had set up in the view achieved what the story was asking for. I would definitely poke around a bit since you had a better grip on what this story was asking for.
